# Generated by Django 5.2.8 on 2025-11-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_event_options_event_created_at_event_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
    ]
